import type { CSSProperties } from "react";

/** Light dashboard + trade table + trade setup (Phase 3+: theme tokens). */
export const dashboardStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f4f7fb",
    color: "#162033",
    fontFamily: "Arial, sans-serif",
  },
  header: {
    background: "linear-gradient(135deg, #0d1b3d, #193362)",
    color: "white",
    padding: "24px 32px",
    marginBottom: "24px",
  },
  headerTitle: {
    margin: 0,
    fontSize: "40px",
    fontWeight: 700,
  },
  headerText: {
    marginTop: "8px",
    color: "#dbe5f6",
    fontSize: "18px",
  },
  wrap: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "0 24px 40px",
  },
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "16px",
    marginBottom: "24px",
  },
  card: {
    background: "white",
    border: "1px solid #d9e1ec",
    borderRadius: "16px",
    padding: "18px",
    boxShadow: "0 1px 2px rgba(16,24,40,.04)",
    marginBottom: "24px",
  },
  kpiLabel: {
    fontSize: "12px",
    color: "#667085",
    textTransform: "uppercase",
    fontWeight: 700,
    letterSpacing: ".04em",
  },
  kpiValue: {
    marginTop: "10px",
    fontSize: "30px",
    fontWeight: 700,
  },
  sectionTitle: {
    fontSize: "20px",
    fontWeight: 700,
    margin: "0 0 16px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "12px",
    alignItems: "center",
  },
  input: {
    padding: "12px 14px",
    border: "1px solid #cfd8e3",
    borderRadius: "10px",
    fontSize: "14px",
    background: "#fff",
  },
  sideButton: {
    padding: "12px 16px",
    borderRadius: "10px",
    border: "1px solid #cfd8e3",
    fontWeight: 700,
    cursor: "pointer",
    minWidth: "100px",
    textAlign: "center",
  },
  longActive: {
    background: "#e6f9f0",
    color: "#067647",
    border: "1px solid #6ce9a6",
  },
  shortActive: {
    background: "#fff1f3",
    color: "#b42318",
    border: "1px solid #fda29b",
  },
  buttonPrimary: {
    background: "#0d1b3d",
    color: "white",
    border: "none",
    borderRadius: "10px",
    padding: "10px 14px",
    fontWeight: 700,
    cursor: "pointer",
    marginRight: "8px",
  },
  buttonGhost: {
    background: "#eef3fb",
    color: "#0d1b3d",
    border: "none",
    borderRadius: "10px",
    padding: "10px 14px",
    fontWeight: 700,
    cursor: "pointer",
    marginRight: "8px",
  },
  buttonWarn: {
    background: "#fff7e6",
    color: "#b54708",
    border: "1px solid #f6d39b",
    borderRadius: "10px",
    padding: "10px 14px",
    fontWeight: 700,
    cursor: "pointer",
    marginRight: "8px",
  },
  buttonDanger: {
    background: "#fff1f3",
    color: "#b42318",
    border: "1px solid #f1bec8",
    borderRadius: "10px",
    padding: "10px 14px",
    fontWeight: 700,
    cursor: "pointer",
    marginRight: "8px",
  },
  mistakesBox: {
    marginTop: "16px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "10px",
  },
  mistakeItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 12px",
    border: "1px solid #d9e1ec",
    borderRadius: "10px",
    background: "#fafbfd",
    fontSize: "14px",
  },
  tableWrap: {
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "8px",
  },
  th: {
    textAlign: "left",
    padding: "12px 10px",
    borderBottom: "1px solid #d9e1ec",
    color: "#667085",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: ".04em",
  },
  td: {
    padding: "12px 10px",
    borderBottom: "1px solid #d9e1ec",
    fontSize: "14px",
    verticalAlign: "top",
  },
  rowActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    alignItems: "center",
  },
  small: {
    color: "#667085",
    fontSize: "13px",
  },
  badge: {
    display: "inline-block",
    padding: "4px 8px",
    borderRadius: "999px",
    background: "#eef3fb",
    color: "#103a78",
    fontSize: "12px",
    fontWeight: 700,
  },
  tradeSetupSubheading: {
    gridColumn: "1 / -1",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: ".06em",
    textTransform: "uppercase",
    color: "#475467",
    marginTop: "8px",
    marginBottom: "0",
  },
  tradeSetupMetricsRow: {
    gridColumn: "1 / -1",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(168px, 1fr))",
    gap: "10px",
    marginTop: "6px",
  },
  tradeSetupMetricTile: {
    background: "linear-gradient(135deg, #0d1b3d, #152a52)",
    border: "1px solid rgba(147, 197, 253, .22)",
    borderRadius: "12px",
    padding: "14px 16px",
    boxShadow: "0 8px 22px rgba(13, 27, 61, .12)",
  },
  tradeSetupMetricLabel: {
    color: "#9bb0d1",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: ".06em",
    textTransform: "uppercase",
  },
  tradeSetupMetricValue: {
    color: "#f0f5ff",
    fontSize: "20px",
    fontWeight: 800,
    marginTop: "8px",
  },
  tradeSetupErrorBanner: {
    gridColumn: "1 / -1",
    margin: 0,
    padding: "10px 12px",
    borderRadius: "10px",
    border: "1px solid #fda29b",
    background: "#fff1f3",
    color: "#b42318",
    fontSize: "13px",
    fontWeight: 700,
  },
  tradeSetupActions: {
    gridColumn: "1 / -1",
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    alignItems: "center",
    marginTop: "4px",
  },
  tradeSetupFieldLabel: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#475467",
    letterSpacing: ".02em",
    textTransform: "uppercase",
    marginBottom: "6px",
    display: "block",
  },
  tradeSetupSymbolRow: {
    gridColumn: "1 / -1",
    display: "grid",
    gridTemplateColumns: "minmax(200px, 1fr) auto",
    gap: "12px",
    alignItems: "end",
    marginBottom: "4px",
  },
  tradeSetupExecGrid: {
    gridColumn: "1 / -1",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "14px",
    marginTop: "4px",
    marginBottom: "4px",
  },
  tradeSetupExecCard: {
    background: "linear-gradient(135deg, #0d1b3d, #152a52)",
    border: "1px solid rgba(147, 197, 253, .28)",
    borderRadius: "14px",
    padding: "18px 20px",
    boxShadow: "0 10px 28px rgba(13, 27, 61, .14)",
  },
  tradeSetupExecLabel: {
    color: "#9bb0d1",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: ".08em",
    textTransform: "uppercase",
  },
  tradeSetupExecValue: {
    color: "#f0f5ff",
    fontSize: "28px",
    fontWeight: 800,
    marginTop: "10px",
    lineHeight: 1.15,
  },
  tradeSetupExecHint: {
    marginTop: "8px",
    color: "#9bb0d1",
    fontSize: "11px",
    fontWeight: 600,
  },
  tradeSetupPositionInput: {
    marginTop: "12px",
    width: "100%",
    boxSizing: "border-box",
    padding: "12px 14px",
    borderRadius: "10px",
    border: "1px solid rgba(147, 197, 253, .35)",
    background: "rgba(15, 27, 51, .65)",
    color: "#f0f5ff",
    fontSize: "16px",
    fontWeight: 700,
    outline: "none",
  },
};

/** ODE + system checks dark panels */
export const odeStyles: Record<string, CSSProperties> = {
  card: {
    background: "linear-gradient(180deg, #0b1220, #0a152d)",
    border: "1px solid rgba(111, 208, 255, .25)",
    borderRadius: "16px",
    padding: "18px",
    boxShadow: "0 10px 30px rgba(0,0,0,.18)",
    marginBottom: "24px",
  },
  panelHeader: {
    display: "flex",
    gap: "12px",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "14px",
  },
  title: {
    color: "white",
    fontWeight: 800,
    fontSize: "18px",
    marginBottom: "4px",
  },
  subtitle: {
    color: "#9bb0d1",
    fontSize: "13px",
    marginTop: "2px",
  },
  outputPanel: {
    background:
      "linear-gradient(180deg, rgba(138, 212, 255, .10), rgba(138, 212, 255, .04))",
    border: "1px solid rgba(138, 212, 255, .30)",
    borderRadius: "14px",
    padding: "12px",
    boxShadow:
      "0 0 0 1px rgba(138, 212, 255, .06), 0 8px 24px rgba(0,0,0,.24)",
    marginBottom: "14px",
  },
  outputLabel: {
    color: "#bfe1ff",
    fontSize: "11px",
    letterSpacing: ".06em",
    textTransform: "uppercase",
    fontWeight: 900,
    marginBottom: "10px",
  },
  outputMeta: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#9bb0d1",
    fontSize: "12px",
    fontWeight: 700,
    marginBottom: "10px",
  },
  liveDot: {
    width: "7px",
    height: "7px",
    borderRadius: "999px",
    background: "#36d399",
    boxShadow: "0 0 0 4px rgba(54,211,153,.18)",
    display: "inline-block",
  },
  step0Box: {
    background: "rgba(255,255,255,.04)",
    border: "1px solid rgba(111, 208, 255, .18)",
    borderRadius: "14px",
    padding: "12px",
    marginBottom: "16px",
  },
  step0Title: {
    color: "#d7ecff",
    fontWeight: 800,
    fontSize: "14px",
    marginBottom: "10px",
  },
  badgePass: {
    display: "inline-block",
    padding: "7px 10px",
    borderRadius: "999px",
    background: "rgba(54, 211, 153, .15)",
    border: "1px solid rgba(54, 211, 153, .35)",
    color: "#36d399",
    fontWeight: 800,
    fontSize: "12px",
  },
  badgeFail: {
    display: "inline-block",
    padding: "7px 10px",
    borderRadius: "999px",
    background: "rgba(248, 113, 113, .15)",
    border: "1px solid rgba(248, 113, 113, .35)",
    color: "#fb7185",
    fontWeight: 800,
    fontSize: "12px",
  },
  checkGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: "10px",
    marginTop: "10px",
  },
  checkItem: {
    background: "rgba(255,255,255,.03)",
    border: "1px solid rgba(255,255,255,.06)",
    borderRadius: "12px",
    padding: "10px 12px",
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "center",
  },
  checkLabel: {
    color: "#e7f0ff",
    fontSize: "13px",
    fontWeight: 700,
  },
  checkStatusPass: {
    color: "#36d399",
    fontSize: "12px",
    fontWeight: 900,
  },
  checkStatusFail: {
    color: "#fb7185",
    fontSize: "12px",
    fontWeight: 900,
  },
  formGrid: {
    display: "flex",
    flexWrap: "nowrap",
    alignItems: "flex-start",
    gap: "12px",
    marginBottom: "14px",
    overflowX: "auto",
    paddingBottom: "4px",
  },
  priceRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "12px",
    alignItems: "start",
    marginBottom: "14px",
  },
  priceInput: {
    background: "#0f1b33",
    border: "1px solid rgba(147, 197, 253, .22)",
    borderRadius: "10px",
    padding: "12px 12px",
    color: "#e7f0ff",
    outline: "none",
    fontSize: "14px",
    width: "100%",
    boxSizing: "border-box",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    flex: "1 1 0",
    minWidth: "180px",
  },
  priceField: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    minWidth: 0,
  },
  label: {
    color: "#d7ecff",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".02em",
    textTransform: "uppercase",
  },
  select: {
    background: "#0f1b33",
    border: "1px solid rgba(147, 197, 253, .22)",
    borderRadius: "10px",
    padding: "12px 12px",
    color: "#e7f0ff",
    outline: "none",
    fontSize: "14px",
  },
  resultGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "12px",
    marginTop: "10px",
  },
  resultCard: {
    background: "rgba(255,255,255,.03)",
    border: "1px solid rgba(255,255,255,.06)",
    borderRadius: "14px",
    padding: "12px",
    minHeight: "86px",
  },
  resultLabel: {
    color: "#9bb0d1",
    fontSize: "12px",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: ".03em",
    marginBottom: "8px",
  },
  resultValue: {
    color: "white",
    fontSize: "20px",
    fontWeight: 900,
  },
  actionValue: {
    fontSize: "15px",
    fontWeight: 900,
    lineHeight: 1.2,
  },
  checksToggle: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "rgba(255,255,255,.03)",
    border: "1px solid rgba(255,255,255,.10)",
    borderRadius: "12px",
    color: "#d7ecff",
    padding: "10px 12px",
    fontWeight: 800,
    cursor: "pointer",
    marginTop: "8px",
    marginBottom: "10px",
  },
  checksHint: {
    color: "#9bb0d1",
    fontSize: "12px",
    fontWeight: 700,
    marginBottom: "8px",
  },
  scoreBreakdown: {
    background: "rgba(255,255,255,.02)",
    border: "1px solid rgba(255,255,255,.06)",
    borderRadius: "14px",
    padding: "12px",
    marginBottom: "12px",
  },
  breakdownTitle: {
    color: "#d7ecff",
    fontWeight: 900,
    fontSize: "13px",
    marginBottom: "10px",
  },
  breakdownRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "10px",
    padding: "7px 0",
    borderBottom: "1px solid rgba(255,255,255,.06)",
    color: "#9bb0d1",
    fontSize: "13px",
    fontWeight: 700,
  },
  breakdownRowLast: {
    borderBottom: "none",
  },
  breakdownPts: {
    color: "#e7f0ff",
    fontWeight: 900,
  },
  noTradeBanner: {
    color: "#fb7185",
    fontWeight: 900,
    background: "rgba(248, 113, 113, .10)",
    border: "1px solid rgba(248, 113, 113, .28)",
    borderRadius: "14px",
    padding: "12px 12px",
    marginBottom: "12px",
  },
  /** Development Progress (Rounds + readiness) — calm, light card. */
  devProgressCard: {
    background: "linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)",
    border: "1px solid #d9e1ec",
    borderRadius: "16px",
    padding: "20px 22px",
    boxShadow: "0 1px 2px rgba(16,24,40,.04)",
    marginBottom: "24px",
  },
  devProgressTop: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "20px",
    alignItems: "start",
  },
  devProgressRoundTitle: {
    margin: 0,
    fontSize: "18px",
    fontWeight: 800,
    color: "#0d1b3d",
    letterSpacing: "-0.02em",
  },
  devProgressSub: {
    margin: "6px 0 0",
    fontSize: "13px",
    color: "#667085",
    lineHeight: 1.45,
  },
  devProgressBarTrack: {
    marginTop: "14px",
    height: "8px",
    borderRadius: "999px",
    background: "#e8eef6",
    overflow: "hidden",
  },
  devProgressBarFill: {
    height: "100%",
    borderRadius: "999px",
    background: "linear-gradient(90deg, #1e3a5f, #2d5a87)",
    transition: "width 0.35s ease",
  },
  devProgressMetrics: {
    display: "grid",
    gap: "12px",
  },
  devProgressMetricLabel: {
    fontSize: "11px",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: ".05em",
    color: "#667085",
  },
  devProgressMetricValue: {
    marginTop: "4px",
    fontSize: "22px",
    fontWeight: 800,
    color: "#0d1b3d",
  },
  devProgressMetricHint: {
    marginTop: "4px",
    fontSize: "12px",
    color: "#667085",
    lineHeight: 1.4,
  },
  devProgressDetails: {
    marginTop: "18px",
    borderTop: "1px solid #e8eef6",
    paddingTop: "14px",
  },
  devProgressSummary: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#344054",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  devProgressDetailBlock: {
    marginTop: "14px",
    padding: "12px 14px",
    background: "#fafbfd",
    borderRadius: "12px",
    border: "1px solid #e8eef6",
    fontSize: "13px",
    color: "#475467",
    lineHeight: 1.5,
  },
  devProgressDetailHeading: {
    fontSize: "11px",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: ".05em",
    color: "#667085",
    marginBottom: "8px",
  },
};
